import { describe, expect, it } from 'vitest';

import type { RegionalThresholds, RiskRequest } from '@/lib/api';
import {
  computeRiskLocal,
  globalDangerLevel,
  regionalBucket,
  scoreV4,
} from '@/lib/risk-local';

import fixture from './fixtures/v4_parity.json';

type ScoreInput = Parameters<typeof scoreV4>[0];

// The load-bearing guard: the TS scorer must reproduce the authoritative
// Python compute_risk. Fixture is generated by scripts/export_v4_fixture.py;
// regenerate it after any RiskParams re-fit. Catches silent backend/frontend
// drift that nothing else would.
describe('scoreV4 ↔ Python compute_risk parity', () => {
  // Guard the guard: it.each([]) registers zero cases and reports green, so a
  // failed/empty fixture export would silently disable the parity check.
  it('fixture is non-empty', () => {
    expect(fixture.length).toBeGreaterThan(0);
  });
  it.each(fixture)('parity case %#', (c) => {
    const { score } = scoreV4(c.input as ScoreInput);
    expect(score).toBeCloseTo(c.expectedScore, 3);
  });
});

describe('regionalBucket', () => {
  const t: RegionalThresholds = {
    low: 0.2,
    moderate: 0.45,
    high: 0.65,
    extreme: 0.8,
    score_max: 0.95,
  };
  it('buckets by percentile cutoffs (HIGH→EXTREME boundary is `extreme`, not `high`)', () => {
    expect(regionalBucket(0.1, t)).toBe('LOW');
    expect(regionalBucket(0.3, t)).toBe('MODERATE');
    expect(regionalBucket(0.7, t)).toBe('HIGH'); // between high(0.65) and extreme(0.8)
    expect(regionalBucket(0.85, t)).toBe('EXTREME');
  });
});

describe('globalDangerLevel', () => {
  it('uses the 0.3 / 0.6 / 0.8 global cutoffs', () => {
    expect(globalDangerLevel(0.1)).toBe('LOW');
    expect(globalDangerLevel(0.45)).toBe('MODERATE');
    expect(globalDangerLevel(0.7)).toBe('HIGH');
    expect(globalDangerLevel(0.9)).toBe('EXTREME');
  });
});

describe('computeRiskLocal', () => {
  const base = {
    temperature: 35,
    humidity: 15,
    wind_speed: 30,
    days_since_rain: 10,
    season: 'summer',
    kbdi: 600,
  } as RiskRequest;

  it('falls back to global (null regional) when no state is given', () => {
    const r = computeRiskLocal(base);
    expect(r.regional_state).toBeNull();
    expect(r.regional_level).toBeNull();
    expect(r.risk_score).toBeGreaterThan(0);
    expect(r.danger_level).toBeTruthy();
  });

  it('attaches a regional bucket for a fitted state', () => {
    const r = computeRiskLocal({ ...base, state: 'CA' });
    expect(r.regional_state).toBe('CA');
    expect(r.regional_level).not.toBeNull();
    expect(r.regional_thresholds).not.toBeNull();
  });
});
